language: java
jdk:
  - oraclejdk8
services:
  - mysql
dist: jessie
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.7
    - mysql-client-core-5.7
    - mysql-core-5.7

before_script:
  mysql -u root -e "CREATE DATABASE CampingTest;"
  mysql -u root -e "CREATE USER camping IDENTIFIED BY 'camping';"
  mysql -u root -e "GRANT ALL PRIVILEGES ON CampingTest.* TO 'camping'@'%';"

